/**
 * Builds the demo registry: every file under `content/demos/<slug>/` becomes a
 * named entry holding both the component and its own source.
 *
 * The source is the point. A doc page used to carry a hand-written string
 * beside each demo — `const basicCode = "..."` next to the JSX that actually
 * rendered — and the two could drift with nothing to catch it. Reading the
 * file the demo lives in means the code panel is showing the demo, not a
 * description of it.
 *
 * Generated rather than resolved at runtime because ComponentPreview is a
 * client component: the source has to be in the bundle, and a `fs.readFile`
 * cannot follow it there.
 */
import { readdirSync, readFileSync, writeFileSync, existsSync } from "node:fs";
import { join } from "node:path";

const ROOT = process.cwd();
const DEMOS = join(ROOT, "content/demos");
const OUT = join(ROOT, "lib/docs/demos.generated.ts");

interface Demo {
  name: string;
  importPath: string;
  identifier: string;
  source: string;
}

function pascal(name: string): string {
  return name
    .split(/[-_]/)
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join("");
}

/** `@/registry/...` -> `@/components/ui/...`, built from the registry's own
 *  `target` fields.
 *
 *  A demo has to import the path that exists in THIS repo to compile, but the
 *  reader copying it wants the path the CLI wrote the component to in THEIRS.
 *  Reading the mapping out of registry.json rather than hardcoding the two
 *  prefixes means the displayed import cannot drift from where `shadcn add`
 *  actually puts the file. */
function registryPathMap(): [string, string][] {
  const registry = JSON.parse(readFileSync(join(ROOT, "registry.json"), "utf8")) as {
    items: { files?: { path: string; target?: string }[] }[];
  };
  const drop = (value: string) => value.replace(/\.(tsx?|jsx?)$/, "");

  return registry.items
    .flatMap((item) => item.files ?? [])
    .filter((file) => file.target && drop(file.target) !== drop(file.path))
    .map((file) => [`@/${drop(file.path)}`, `@/${drop(file.target as string)}`] as [string, string])
    // Longest first, so a path that prefixes another cannot be partly rewritten.
    .sort(([a], [b]) => b.length - a.length);
}

const pathMap = registryPathMap();

function displaySource(source: string): string {
  let out = source
    // A compiler directive, not part of the sample - a reader copying the
    // block does not want it, and every demo carries one.
    .replace(/^"use client";\n\n?/, "")
    .trimEnd();
  for (const [from, to] of pathMap) out = out.replaceAll(from, to);
  return out;
}

const demos: Demo[] = [];

if (existsSync(DEMOS)) {
  for (const slug of readdirSync(DEMOS).sort()) {
    const dir = join(DEMOS, slug);
    for (const file of readdirSync(dir).sort()) {
      if (!file.endsWith(".tsx")) continue;
      const name = file.replace(/\.tsx$/, "");
      demos.push({
        name,
        importPath: `@/content/demos/${slug}/${name}`,
        identifier: `Demo${pascal(slug)}${pascal(name)}`,
        source: displaySource(readFileSync(join(dir, file), "utf8")),
      });
    }
  }
}

const body = `// Generated by scripts/build-demos.ts — do not edit by hand.
// Run \`make demos\` after adding or renaming a demo. \`make dev\` and
// \`make build\` regenerate it, and \`make test\` fails if it has drifted.
import type { ComponentType } from "react";

${demos.map((d) => `import ${d.identifier} from "${d.importPath}";`).join("\n")}

export interface DemoEntry {
  Component: ComponentType;
  /** The demo file's own source — what the preview's code panel shows. */
  source: string;
}

/** Every demo, keyed by the name a doc page refers to it by. */
export const demos: Record<string, DemoEntry> = {
${demos
  .map((d) => `  ${JSON.stringify(d.name)}: {\n    Component: ${d.identifier},\n    source: ${JSON.stringify(d.source)},\n  },`)
  .join("\n")}
};
`;

writeFileSync(OUT, body);
console.log(`✔ Demos: ${demos.length} across ${existsSync(DEMOS) ? readdirSync(DEMOS).length : 0} components.`);
