/**
 * Builds every page's table of contents at build time, so the list ships
 * inside the server-rendered HTML instead of being discovered from the DOM
 * after hydration. Reading it from the DOM was what made the panel flicker:
 * the scan could only run after the first paint, so the page painted without
 * a contents list and then grew one.
 *
 * This used to walk the TypeScript syntax tree of each page.tsx looking for
 * the three components that render an anchored heading, because the headings
 * lived in JSX. They are markdown now, so it reads the `##` lines directly.
 *
 * The ids come from github-slugger, which is what rehype-slug uses to stamp
 * the headings themselves at compile time. The two have to agree exactly or
 * every link in the panel misses its heading — hence the shared library
 * rather than a second implementation of the same rules.
 */
import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

import GithubSlugger from "github-slugger";

import type { TocEntry } from "../lib/docs/heading-id";

const ROOT = process.cwd();
const CONTENT = join(ROOT, "content/docs");
const OUT = join(ROOT, "lib/docs/toc.generated.ts");

/** The route a content file backs. The two section pages keep bespoke chrome
 *  and their own routes; every other file is a component slug. */
function routeFor(name: string): string {
  if (name === "introduction") return "/docs";
  return `/docs/${name}`;
}

function headingsOf(source: string): TocEntry[] {
  const slugger = new GithubSlugger();
  const entries: TocEntry[] = [];
  let inFence = false;

  for (const line of source.split("\n")) {
    // A `##` inside a fenced block is code, not a heading.
    if (/^\s*(```|~~~)/.test(line)) {
      inFence = !inFence;
      continue;
    }
    if (inFence) continue;

    const match = /^(#{2,3})\s+(.+?)\s*$/.exec(line);
    if (!match) continue;

    // Strip the inline markup a heading may carry (`code`, **bold**) so the
    // panel prints the words rather than the syntax.
    const text = match[2]
      .replace(/`([^`]+)`/g, "$1")
      .replace(/\*\*([^*]+)\*\*/g, "$1")
      .trim();

    entries.push({
      id: slugger.slug(text),
      text,
      depth: match[1].length as 2 | 3,
    });
  }

  return entries;
}

/** Every page's headings, keyed by route. Exported so the test can rebuild it
 *  in memory and compare against the committed file — the manifest goes stale
 *  the moment a heading is added or renamed, and that comparison is the only
 *  thing that catches it. */
export function collectToc(): Record<string, TocEntry[]> {
  const toc: Record<string, TocEntry[]> = {};
  for (const file of readdirSync(CONTENT).sort()) {
    if (!file.endsWith(".mdx")) continue;
    const name = file.replace(/\.mdx$/, "");
    toc[routeFor(name)] = headingsOf(readFileSync(join(CONTENT, file), "utf8"));
  }
  return toc;
}

const toc = collectToc();

const body = `// Generated by scripts/build-toc.ts — do not edit by hand.
// Run \`make toc\` after adding or renaming a section. \`make dev\` and
// \`make build\` regenerate it, and \`make test\` fails if it has drifted.
import type { TocEntry } from "@/lib/docs/heading-id";

/** Every page's headings, in reading order, keyed by route. */
export const TOC: Record<string, TocEntry[]> = ${JSON.stringify(toc, null, 2)};
`;

// Only when run as a script: the test imports `collectToc` from here, and an
// import that rewrote the generated file would make the drift check compare
// the manifest against itself.
if ((import.meta as ImportMeta & { main?: boolean }).main) {
  writeFileSync(OUT, body);
  const count = Object.values(toc).reduce((n, entries) => n + entries.length, 0);
  console.log(`✔ Table of contents: ${count} headings across ${Object.keys(toc).length} pages.`);
}
