// Generated by scripts/build-toc.ts — do not edit by hand.
// Run `make toc` after adding or renaming a section. `make dev` and
// `make build` regenerate it, and `make test` fails if it has drifted.
import type { TocEntry } from "@/lib/docs/heading-id";

/** Every page's headings, in reading order, keyed by route. */
export const TOC: Record<string, TocEntry[]> = {
  "/docs/button": [
    { id: "installation", text: "Installation", depth: 2 },
    { id: "playground", text: "Playground", depth: 2 },
    { id: "variants", text: "Variants", depth: 2 },
    { id: "with-icons", text: "With Icons", depth: 2 },
    { id: "loading-&-disabled", text: "Loading & Disabled", depth: 2 },
    { id: "api-reference", text: "API Reference", depth: 2 },
  ],
  "/docs/code": [
    { id: "installation", text: "Installation", depth: 2 },
    { id: "basic", text: "Basic", depth: 2 },
    { id: "with-a-filename", text: "With a filename", depth: 2 },
    { id: "package-managers", text: "Package managers", depth: 2 },
    { id: "custom-theme", text: "Custom theme", depth: 2 },
    { id: "expandable", text: "Expandable", depth: 2 },
    { id: "api-reference", text: "API Reference", depth: 2 },
  ],
  "/docs/product-card": [
    { id: "installation", text: "Installation", depth: 2 },
    { id: "basic", text: "Basic", depth: 2 },
    { id: "inner-layout", text: "Inner layout", depth: 2 },
    { id: "badge", text: "Badge", depth: 2 },
    { id: "grid", text: "Grid", depth: 2 },
    { id: "sizes", text: "Sizes", depth: 2 },
    { id: "api-reference", text: "API Reference", depth: 2 },
    { id: "parts", text: "Parts", depth: 2 },
  ],
  "/docs/switch": [
    { id: "installation", text: "Installation", depth: 2 },
    { id: "basic", text: "Basic", depth: 2 },
    { id: "disabled", text: "Disabled", depth: 2 },
    { id: "api-reference", text: "API Reference", depth: 2 },
  ],
  "/docs/tabs": [
    { id: "installation", text: "Installation", depth: 2 },
    { id: "basic", text: "Basic", depth: 2 },
    { id: "underline", text: "Underline", depth: 2 },
    { id: "ghost", text: "Ghost", depth: 2 },
    { id: "concentric", text: "Concentric", depth: 2 },
    { id: "sizes", text: "Sizes", depth: 2 },
    { id: "with-icons", text: "With Icons", depth: 2 },
    { id: "animated-panels", text: "Animated panels", depth: 2 },
    { id: "api-reference", text: "API Reference", depth: 2 },
  ],
  "/docs/tooltip": [
    { id: "installation", text: "Installation", depth: 2 },
    { id: "basic", text: "Basic", depth: 2 },
    { id: "placement", text: "Placement", depth: 2 },
    { id: "rich-content", text: "Rich Content", depth: 2 },
    { id: "follow-cursor", text: "Follow cursor", depth: 2 },
    { id: "delay", text: "Delay", depth: 2 },
    { id: "api-reference", text: "API Reference", depth: 2 },
  ],
};
